"use strict";
exports.__esModule = true;
exports.sinWave = exports.sextic = exports.quintic = exports.quartic = exports.cubic = exports.quad = exports.linear = void 0;
var factory_1 = require("./factory");
exports.linear = factory_1.I;
exports.quad = (0, factory_1.exp)(2);
exports.cubic = (0, factory_1.exp)(3);
exports.quartic = (0, factory_1.exp)(4);
exports.quintic = (0, factory_1.exp)(5);
exports.sextic = (0, factory_1.exp)(6);
exports.sinWave = (0, factory_1.sine)(1);
